"""empty message

Revision ID: 21e6fa5ce342
Revises: 47aafbcee435
Create Date: 2024-04-18 19:33:21.936298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21e6fa5ce342'
down_revision = '47aafbcee435'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_constraint('chat_user_sender_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('chat_user_reciver_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_sender_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'users', ['user_reciver_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('chat_user_reciver_id_fkey', 'users', ['user_reciver_id'], ['id'])
        batch_op.create_foreign_key('chat_user_sender_id_fkey', 'users', ['user_sender_id'], ['id'])

    # ### end Alembic commands ###
